// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnedArticles = `-- name: CountOwnedArticles :one
SELECT count(*) FROM articles
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR title ILIKE '%' || $3 || '%')
`

type CountOwnedArticlesParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
}

func (q *Queries) CountOwnedArticles(ctx context.Context, arg CountOwnedArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedArticles, arg.UserID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (user_id, title, body, summary)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, body, status, created_at, updated_at, summary
`

type CreateArticleParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Title   string    `json:"title"`
	Body    string    `json:"body"`
	Summary string    `json:"summary"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Summary,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :execrows
DELETE FROM articles WHERE id = $1 AND user_id = $2
`

type DeleteArticleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArticle, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnedArticle = `-- name: GetOwnedArticle :one
SELECT id, user_id, title, body, status, created_at, updated_at, summary FROM articles WHERE id = $1 AND user_id = $2
`

type GetOwnedArticleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOwnedArticle(ctx context.Context, arg GetOwnedArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, getOwnedArticle, arg.ID, arg.UserID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
	)
	return i, err
}

const listOwnedArticles = `-- name: ListOwnedArticles :many
SELECT id, user_id, title, body, status, created_at, updated_at, summary FROM articles
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR title ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListOwnedArticlesParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListOwnedArticles(ctx context.Context, arg ListOwnedArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listOwnedArticles,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArticleIfDraft = `-- name: PublishArticleIfDraft :execrows
UPDATE articles SET status = 'published', updated_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'draft'
`

type PublishArticleIfDraftParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) PublishArticleIfDraft(ctx context.Context, arg PublishArticleIfDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishArticleIfDraft, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = coalesce($3, title),
    body = coalesce($4, body),
    summary = coalesce($5, summary),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, body, status, created_at, updated_at, summary
`

type UpdateArticleParams struct {
	ID      uuid.UUID   `json:"id"`
	UserID  uuid.UUID   `json:"user_id"`
	Title   pgtype.Text `json:"title"`
	Body    pgtype.Text `json:"body"`
	Summary pgtype.Text `json:"summary"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Summary,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
	)
	return i, err
}
